#!/bin/bash
sudo apt update;
sudo apt install xfce4 xfce4-goodies;
sudo apt install tightvncserver;
vncserver;
vncserver -kill :1;
mv ~/.vnc/xstartup ~/.vnc/xstartup.bak;
mv ~/aws/xstartup ~/.vnc/;
chmod +x ~/.vnc/xstartup;
vncserver -localhost;
cd ~/ && wget https://redirector.gvt1.com/edgedl/android/studio/ide-zips/2021.3.1.17/android-studio-2021.3.1.17-linux.tar.gz;
tar -xf android-studio-2021.3.1.17-linux.tar.gz;
sudo rm android-studio-2021.3.1.17-linux.tar.gz;
cd ~/android-studio/bin && cd bin && ./studio.sh;
