#!/bin/bash
sudo apt update;
sudo apt install xfce4 xfce4-goodies;
sudo apt install tightvncserver;
vncserver;
vncserver -kill :1;
mv ~/.vnc/xstartup ~/.vnc/xstartup.bak;
mv ~/aws/xstartup ~/.vnc/;
chmod +x ~/.vnc/xstartup;
vncserver -localhost;
cd;
